name: Download a file using dotnet-file
author: David G. Moore, Jr., <david@dgmjr.io>
description: Downloads global.json using the dotnet-file tool

inputs:
  token:
    type: string
    name: token

runs:
  using: composite
  steps: 
    - id: Download-global-json
      uses: dgmjr-actions/download-a-file-using-dotnet-file@main
      with: 
        repo: dgmjr-io/dgmjr-io
        filename: tree/main/global.json
        token: ${{ inputs.token }}
        
